
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost
  port: 5432
  database: nerdgear

development:
  <<: *default

test:
  <<: *default
  database: nerdgear_test

production:
  <<: *default
  url: postgres://edructqejyzwnt:6rdsiCqORtUFTySccmW55OxK7E@ec2-54-83-0-187.compute-1.amazonaws.com:5432/d65o8m6ptb5co
